### ISSUE TITLE
Table Index in Readme

### ISSUE THREAD

**Issue by antfu** [g-plane/type-gymnastics#1]
It would be great if we could have a table indexing those parsers and their authors (and maybe a brief intro).

And would love to introduce in the [Type Challenges](https://github.com/type-challenges/type-challenges) readme. Wondering what you think 😉

**Comment by g-plane** [comment]
That's a good idea, but I'm not sure whether should be auto-generated or update manually.

**Comment by antfu** [comment]
I would say that simply doing them manually would be good for now.

**Comment by g-plane** [comment]
I agree!
